import{a as q,S as E,i as l}from"./assets/vendor-b11e2a50.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const P="44743173-b0da996c95212aae97675bf04",T="https://pixabay.com/api/";async function f(t,r=1,s=15){try{return(await q.get(T,{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s}})).data}catch(i){throw console.error("Error fetching images:",i),i}}let d;function m(t){const r=document.querySelector(".gallery"),s=t.map(({webformatURL:i,largeImageURL:e,tags:o,likes:a,views:S,comments:L,downloads:v})=>`
    <div class="photo-card">
      <a href="${e}">
        <img class="card-img" src="${i}" alt="${o}" loading="lazy" />
      </a>
      <div class="card-info">
        <p class="info-item"><b>Likes</b> ${a}</p>
        <p class="info-item"><b>Views</b> ${S}</p>
        <p class="info-item"><b>Comments</b> ${L}</p>
        <p class="info-item"><b>Downloads</b> ${v}</p>
      </div>
    </div>
    `).join("");r.insertAdjacentHTML("beforeend",s),d?d.refresh():d=new E(".gallery a")}function $(){const t=document.querySelector(".gallery");t.innerHTML=""}const p=document.querySelector("#search-form"),y=p.querySelector(".form-input"),g=document.querySelector("#loader"),n=document.querySelector("#load-more");let c=1,h="",b=0;p.addEventListener("submit",async t=>{t.preventDefault();const r=y.value.trim();if(r===""){l.error({title:"Error",message:"Please enter a search query",position:"center"});return}h=r,c=1,$(),w(),n.style.display="none",y.value="";try{const s=await f(r,c);setTimeout(()=>{if(u(),s.hits.length===0){l.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"center"});return}b=s.totalHits,m(s.hits),s.hits.length>0&&(n.style.display="block")},2e3)}catch{setTimeout(()=>{u(),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"center"})},2e3)}});n.addEventListener("click",async()=>{c++,w(),n.style.display="none";try{const t=await f(h,c);setTimeout(()=>{u(),m(t.hits),c*15>=b?(n.style.display="none",l.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"center"})):n.style.display="block",O()},2e3)}catch{setTimeout(()=>{u(),l.error({title:"Error",message:"Something went wrong. Please try again later.",position:"center"})},2e3)}});function w(){g.style.display="block"}function u(){g.style.display="none"}function O(){const t=document.querySelector(".gallery").firstElementChild;if(t){const r=t.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})}}
//# sourceMappingURL=commonHelpers.js.map
